clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="lain.home.arpa"
keymap="us.kbd"
moused_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
zfs_enable="YES"
