clear_tmp_enable="YES"
syslogd_flags="-ss"
hostname="lain.home.arpa"
keymap="us.kbd"
#ifconfig_em0="DHCP"
#ifconfig_em0_ipv6="inet6 accept_rtadv"
moused_enable="YES"
# Set dumpdev to "AUTO" to enable crash dumps, "NO" to disable
dumpdev="AUTO"
