# Personal
permit persist keepenv yukiteru as root

# Wireguard control
permit nopass yukiteru as root cmd /usr/local/bin/wireguardctl args up
permit nopass yukiteru as root cmd /usr/local/bin/wireguardctl args down

# Wireless control
permit nopass yukiteru as root cmd /usr/local/bin/wirelessctl args up
permit nopass yukiteru as root cmd /usr/local/bin/wirelessctl args down

