#!/usr/bin/env bash

## Author : Aditya Shakya (adi1090x)
## Github : @adi1090x
#
## Rofi   : Power Menu
#
## Available Styles
#
## style-1   style-2   style-3   style-4   style-5

# Current Theme
dir="$HOME/.config/rofi/powermenu/type-1"
theme='style-2'

# CMDs
uptime="`uptime | cut -d " " -f 6-11`"
host=`hostname`

# Options
shutdown='󰐥 Shutdown'
reboot='󰤁 Reboot'
lock='󱅞  Lock'
logout='󰍃 Logout'
novpn='  No VPN'
vpnwork='  VPN Work'
wireguard='  Wireguard Personal'
yes='  Yes'
no='  No'

# Rofi CMD
rofi_cmd() {
	rofi -dmenu \
		-p "$host" \
		-mesg "Uptime: $uptime" \
		-theme ${dir}/${theme}.rasi
}

# Confirmation CMD
confirm_cmd() {
	rofi -theme-str 'window {location: center; anchor: center; fullscreen: false; width: 250px;}' \
		-theme-str 'mainbox {children: [ "message", "listview" ];}' \
		-theme-str 'listview {columns: 2; lines: 1;}' \
		-theme-str 'element-text {horizontal-align: 0.5;}' \
		-theme-str 'textbox {horizontal-align: 0.5;}' \
		-dmenu \
		-p 'Confirmation' \
		-mesg 'Are you Sure?' \
		-theme ${dir}/${theme}.rasi
}

# Ask for confirmation
confirm_exit() {
	echo -e "$yes\n$no" | confirm_cmd
}

# Pass variables to rofi dmenu
run_rofi() {
	echo -e "$lock\n$logout\n$reboot\n$shutdown\n$novpn\n$vpnwork\n$wireguard" | rofi_cmd
}

# Execute Command
run_cmd() {
	selected="$(confirm_exit)"
	if [[ "$selected" == "$yes" ]]; then
		if [[ $1 == '--shutdown' ]]; then
			shutdown -p now
		elif [[ $1 == '--reboot' ]]; then
			shutdown -r now
		elif [[ $1 == '--logout' ]]; then
			i3-msg exit
		fi
	else
		exit 0
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $shutdown)
		run_cmd --shutdown
        ;;
    $vpnwork)
		doas /usr/local/bin/wireguard-control work
        ;;
    $wireguard)
		doas /usr/local/bin/wireguard-control personal
        ;;
    $novpn)
		doas /usr/local/bin/wireguard-control novpn
        ;;
    $reboot)
		run_cmd --reboot
        ;;
    $lock)
		i3lock -t -i /home/yukiteru/.lock.png --color=000000
        ;;
    $logout)
		run_cmd --logout
        ;;
esac
