# apply mark for Xwayland and wayland native browser windows
for_window [class="chromium"]		mark Browser
for_window [class="Firefox"]		mark Browser
for_window [app_id="chromium"]		mark Browser
for_window [app_id="Firefox"]		mark Browser

# inhibit scrensaver for fullscreen browser windows
for_window [con_mark="Browser"] {
	inhibit_idle fullscreen
}

# firefox wayland screensharing indicator
for_window [app_id="Firefox" title="Firefox — Sharing Indicator"] {
	floating enable
}

for_window [app_id="ncmpcpp"] {
	floating enable
}

