# apply mark for Xwayland and wayland native browser windows
for_window [class="chromium|chromium-browser"]            mark Browser
for_window [class="Firefox"]                              mark Browser
for_window [app_id="chromium|chromium-browser"]           mark Browser
for_window [app_id="Firefox"]                             mark Browser

####################################################
# Defaults containers
####################################################

# Apps move to containers
assign [app_id="org.telegram.desktop"] 3
assign [app_id="firefox"] 4
assign [app_id="^thunderbird$"] 5
assign [app_id="libreoffice"] 5
assign [app_id="gimp"] 5

####################################################
# Windows rules
####################################################

for_window [app_id="gnome-calculator"] floating enable
for_window [window_role="pop-up"] floating enable
for_window [window_role="bubble"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [window_role="Preferences"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable

# Multimedia
for_window [app_id="(?i)mpv"] floating enable
for_window [app_id="pavucontrol|org.pulseaudio.pavucontrol"] floating enable
for_window [app_id="vlc"] floating enable
for_window [instance="vlc"] floating enable

# File chooser
for_window [window_role="GtkFileChooserDialog"] resize set 800 600
for_window [window_role="GtkFiileChooserDialog"] move position center

####################################################
# Other rules
####################################################

# inhibit scrensaver for fullscreen browser windows
for_window [con_mark="Browser"] {
	inhibit_idle fullscreen
}

# firefox wayland screensharing indicator
for_window [app_id="Firefox" title="Firefox — Sharing Indicator"] {
	floating enable
}

for_window [app_id="ncmpcpp"] {
	floating enable
  move position center
}
