#!/usr/bin/env bash

LAN_IF="em0"
WLAN_IF="wlan0"
#PARENT_IF="iwlwifi0"
PARENT_IF="iwx0"


case "$1" in
    up)
        if [ "$EUID" -ne 0 ]; then
            echo "Error: Requiere root."
            exit 1
        fi
        echo "Cambiando a modo inalámbrico (WiFi)..."

        # 1. Apagamos por completo el DHCP de la LAN y bajamos la interfaz
        if [ -f "/var/run/dhclient.${LAN_IF}.pid" ]; then
            kill $(cat /var/run/dhclient.${LAN_IF}.pid) >/dev/null 2>&1
        fi
        ifconfig $LAN_IF down
        ifconfig $LAN_IF delete >/dev/null 2>&1 # Remueve la IP vieja de la tabla

        # 2. Creamos y levantamos el nodo Wi-Fi
        if ! ifconfig $WLAN_IF > /dev/null 2>&1; then
            ifconfig $WLAN_IF create wlandev $PARENT_IF group egress
        fi
        ifconfig $WLAN_IF up

        # 3. Autenticación
        if ! pgrep -q wpa_supplicant; then
            wpa_supplicant -s -B -i $WLAN_IF -c /usr/local/etc/wpa_supplicant.d/wpa_homemp_2ax.conf
            sleep 1
        fi

        # 4. Forzamos una tabla de rutas limpia antes de pedir IP
        route flush >/dev/null 2>&1
        dhclient $WLAN_IF
	service routing restart

        # 5. Sincronizar PF
        pfctl -F all && pfctl -f /etc/pf.conf
        echo "WiFi Activo con tabla de rutas limpia."
        ;;

    down)
        if [ "$EUID" -ne 0 ]; then
            echo "Error: Requiere root."
            exit 1
        fi
        echo "Cambiando a modo cableado (LAN)..."

        # 1. Limpieza total de la interfaz Wi-Fi
        if [ -f "/var/run/dhclient.${WLAN_IF}.pid" ]; then
            kill $(cat /var/run/dhclient.${WLAN_IF}.pid) >/dev/null 2>&1
        fi
        if pgrep -q wpa_supplicant; then
            killall wpa_supplicant
        fi
        
        if ifconfig $WLAN_IF > /dev/null 2>&1; then
            ifconfig $WLAN_IF destroy
        fi

        # 2. Forzamos limpieza de rutas muertas antes de levantar la LAN
        route flush >/dev/null 2>&1

        # 3. Levantamos la LAN física
        ifconfig $LAN_IF up
        dhclient $LAN_IF

	service routing restart

        # 4. Sincronizar PF
        pfctl -F all && pfctl -f /etc/pf.conf
        echo "LAN Activa. WiFi destruida y rutas saneadas."
        ;;

    status)
        echo "====================================================="
        echo " INTERFAZ FÍSICA CON IP ASIGNADA"
        echo "====================================================="
        if ifconfig $LAN_IF 2>/dev/null | grep -q "inet "; then
            echo "-> ESTADO: Conectado por CABLE ($LAN_IF)"
            ifconfig $LAN_IF | grep "inet "
        elif ifconfig $WLAN_IF 2>/dev/null | grep -q "inet "; then
            echo "-> ESTADO: Conectado por Wi-Fi ($WLAN_IF)"
            ifconfig $WLAN_IF | grep -E "(inet |ssid )"
        else
            echo "-> ESTADO: Desconectado o sin IP asignada."
        fi
        ;;
    *)
        echo "Uso: $0 {up|down|status}"
        exit 1
        ;;
esac
