monitor.oss.rules = [
  {
    matches = [
      {
        -- Este es para el Micrófono/Entrada
        node.name = "oss_input.dsp3"
      }
    ],
    actions = {
      update-props = {
        priority.driver = 1500,
        priority.session = 1500
      }
    }
  },
  {
    matches = [
      {
        -- Este es para los Altavoces/Salida
        node.name = "oss_output.dsp3"
      }
    ],
    actions = {
      update-props = {
        priority.driver = 1500,
        priority.session = 1500
      }
    }
  }
]
